class EventConstants {}

EventConstants.RESET_BOATS = "RESET_BOATS";
EventConstants.SELECT_BOAT = "SELECT_BOAT";
EventConstants.MOUSE_OVER_BOAT = "MOUSE_OVER_BOAT";
EventConstants.MOUSE_LEAVE_BOAT = "MOUSE_LEAVE_BOAT";

EventConstants.MOUSE_OVER_AVAILABLE_BOARD_LOCATION =
  "MOUSE_OVER_AVAILABLE_BOARD_LOCATION";

EventConstants.MOUSE_OVER_UNAVAILABLE_BOARD_LOCATION =
  "MOUSE_OVER_UNAVAILABLE_BOARD_LOCATION";

EventConstants.RESET_COLOR_FOR_BOARD_LOCATIONS =
  "RESET_COLOR_FOR_BOARD_LOCATIONS";

EventConstants.GAME_SETUP_FINISHED = "GAME_SETUP_FINISHED";

EventConstants.SELECT_LOCATIONS = "SELECT_LOCATIONS";
EventConstants.START_GAME = "START_GAME";

EventConstants.PLAYER_SHOT = "PLAYER_SHOT";
EventConstants.COMPUTER_SHOT = "COMPUTER_SHOT";
EventConstants.NEW_NOTIFICATION = "NEW_NOTIFICATION";

EventConstants.COMPUTER_WIN = "COMPUTER_WIN";

EventConstants.HUMAN_WIN = "HUMAN_WIN";

Object.freeze(EventConstants);

export default EventConstants;
